### PR TITLE
fix broken files and changed all references to litecoin to maplecoin

### PR DESCRIPTION
**Pull request by owlhooter**

### CODE REVIEW

**Comment by dataman** [comment]
Cool,

But would please put me in contact with your team?
Who previously compiled mac or android for you?
I need a bit of help getting this working.

**Comment by owlhooter** [comment]
I'm usually monitoring the IRC channel and am willing to help when I can, I haven't done a mac wallet or android before though, but was going to at least look into the mac part probably this next week if I have the time, can't guarantee I'll get anything accomplished with it though.

**Comment by dataman** [comment]
OwlHooter,

I've been seeing your name popping up in my pool (cryptoadhd) as well.
Hail and well met, I'm Dataman.

I'm looking for just a little help on the compilers.

Seems that windows code is compiled in Linux (at least according the Litecoin master)
What platform and toolset are you using to compile?
Any advice?

I think I'm nearly there on compiling the mac version.
I've got one or two library problems to resolve,
My chief concern is that the master branch compile on OSX 10.5 for compatibility.
I'm running 10.9

**Comment by owlhooter** [comment]
I'm the admin of the CryptoADHD pool.  With the windows compile I actually built it in a Windows Virtual machine I setup, I had been trying to get it to compile with Gitian following the limited instructions I could find and kept getting errors that I have been unable to resolve at this point.  But it seems to have compiled well in my windows test environment, so I'm happy with that.

**Comment by dataman** [comment]
I'm Dataman on your pools.
Nice job running the pools, thank you!
Just a stumbling hacker with a 14 stick farm.

What compiler are you using in Windows?
Doesn't seem to like Visual Studio 2013.
From the notes on Litecoin,
They want to do the compile in Linux,
So I built up an ubuntu virtual, and started building the libraries.

**Comment by owlhooter** [comment]
https://bitcointalk.org/index.php?topic=149479.0  is the instructions I used to compile in windows, had to use mingw32 and it compiles in a linux environment on windows.  I had trouble with some of the steps on there when setting up, but I've slept since then and can't remember which ones I had trouble with or how I got it working, but it works best in a clean environment as I initially just tried on my desktop and kept failing, after setting up a clean VM with Windows 7 it seems to have run better.

**Comment by dataman** [comment]
mingw, Yup that's the path I've been going down.
Looks like the motherload on compile instructions.
Awesome.
That's what I was looking for

**Pull request merged**
